# .github/workflows/ci-cd-pipeline.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Code Coverage
      run: npm run coverage

  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Deploy to Staging
      run: |
        echo "Deploying to Staging Environment"
        # Add deployment script here, e.g., SSH, FTP, or cloud deployment command

  
  notify:
    runs-on: ubuntu-latest
    needs: [build, test, deploy]
    if: failure()  # Run only if any previous jobs failed
    
    steps:
    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        text: |
          :red_circle: CI/CD Pipeline Failed
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Job: ${{ github.job }}
          <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}> View details
